#+title: Curriculum Vitae with Org-mode
#+author: Laurent Lejeune

Shameless fork of [[https://github.com/zzamboni/vita][zzamboni/vita]].

This repository contains the source for my CV. The document is maintained in org-mode. The main export format is to LaTeX and PDF.

The export to LaTeX is done using the [[https://github.com/posquit0/Awesome-CV][AwesomeCV]] LaTeX class (with some of my own modifications, which you can find in this directory) and the [[https://titan-c.gitlab.io/org-cv/#using-awesomecv][ox-awesomecv]] exporter I contributed to the [[https://titan-c.gitlab.io/org-cv/][Org-CV]] package.

* org-mode configuration

Org-CV is not available in MELPA yet, so I it must be installed from its [[https://gitlab.com/Titan-C/org-cv][gitlab repository]]. I use Doom Emacs, so I install it using the =package!= command in the =packages.el= file:

#+begin_src emacs-lisp
(package! org-cv
  :recipe (:host gitlab
           :repo "Titan-C/org-cv"))
#+end_src

Once installed, I load it using the =use-package!= command:

#+begin_src emacs-lisp
(use-package! ox-awesomecv
  :after org)
#+end_src

If you don't use Doom Emacs, you can clone the git repository under =~/.emacs.d/lisp/org-cv=, and then use the following code to load the modules:

  #+begin_src emacs-lisp
(use-package ox-awesomecv
  :load-path "~/.emacs.d/lisp/org-cv"
  :init (require 'ox-awesomecv))
  #+end_src

* LaTeX configuration

You need a functional LaTeX install. AwesomeCV requires the use of XeTeX or LuaTeX. I currently use [[https://tectonic-typesetting.github.io/en-US/][Tectonic]], but you can also use the [[https://www.tug.org/texlive/][TeXLive distribution]], which contains all the base packages and binaries, or [[https://yihui.org/tinytex/][TinyTeX]], which allows you only install the packages you need.

This repository contains a slightly customized version of the Awesome-CV package. The LaTeX files are in the =texinput= directory, so you need to add it to the =$TEXINPUT= environment variable for the compile to work (Tectonic does not support =TEXINPUT=, so they are also symlinked into the main directory so they can be found). Tectonic itself takes care of all the compilation phases, but you can also use =latexmk= (included in the TeXLive distribution) to handle the document compilation, you can see its configuration file in [[./.latexmkrc][.latexmkrc]]. I have also put together a simple [[./Makefile][Makefile]] to compile the document, and to automate publishing the latest version of my CV to [[https://zzamboni.org/vita/][my website]].

* Document structure

Some things you may find useful:

- By Org-CV convention, the title of the org-document (as specified by =#+title=) is used for the "desired job/position", since your name is specified using the =#+author= document property.
- You can specify many other properties (e.g. mobile phone, twitter profile, email address, home page URL, etc.) using other document properties. Some are supported by all Org-CV modules, others only by the AwesomeCV exporter, see the [[https://titan-c.gitlab.io/org-cv/][Org-CV]] documentation for the general properties, and the [[https://titan-c.gitlab.io/org-cv/#using-awesomecv][AwesomeCV section]] for the =ox-awesomecv= specifics.
- At the top of the Org document there is a block starting with =:CV_CONFIG:=. This block contains all the global document properties to specify AwesomeCV, org-mode and LaTeX configuration properties. The block is optional, I use it only so I can easily collapse the whole block in Emacs when I don't need it.
- The "Private info" section contains private information which should not be included in the CV by default. It is kept encrypted, so that even if the source file is publicly visible (like mine), the private information is kept protected. The encryption is done automatically thanks to the =org-crypt= Emacs package. The =crypt= tag in the "Private info" section causes it to be encrypted automatically every time the file is saved, and the =noexport= tag in its enclosing section causes it to be omitted when the file gets exported. Its contents, when unencrypted, contains field definitions like this:
  #+begin_example
    ,#+mobile: <my mobile number>
    ,#+address: <my address>
    ,#+extrainfo: <other private information>
#+end_example

- Org-CV does not yet have integration into the org-mode Export menu. For now, the export is done manually by executing a command like the following:
  #+begin_src emacs-lisp
(org-export-to-file 'awesomecv "zamboni-vita.tex")
  #+end_src
- You can automate the export by adding an after-save hook to run the export every time you save the org file. To do this, add the following code at the end of the document (see my org file for an example):
  #+begin_src org
    ,* Local Variables :ARCHIVE:noexport:
    # Local Variables:
    # eval: (add-hook 'after-save-hook (lambda () (org-export-to-file 'awesomecv "lejeune-vita.tex")) :append :local)
    # End:
  #+end_src
